# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='poked_users',
            field=models.ManyToManyField(related_name='_user_poked_users_+', to='login_reg.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='users_poked',
            field=models.ManyToManyField(related_name='_user_users_poked_+', to='login_reg.User'),
        ),
    ]
