# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_auto_20171222_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('poked_users', models.ManyToManyField(related_name='_users_poked_users_+', to='login_reg.Users')),
                ('users_poked', models.ManyToManyField(related_name='_users_users_poked_+', to='login_reg.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='poked_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='users_poked',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
