# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0005_auto_20171222_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='times_poked',
        ),
        migrations.AddField(
            model_name='users',
            name='times_poked',
            field=models.IntegerField(null=True),
        ),
    ]
